### ISSUE TITLE
looking for a volunteer to translate create-react-library docs in chinese

### ISSUE THREAD

**Issue by transitive-bullshit** [monsterooo/react-statements#1]
Hey, just checking in on various modules created with create-react-library -- this definitely looks really useful :)

I was wondering if you had any interest in adding a Chinese version of the create-react-library readme?

No worries either way 💯

**Comment by monsterooo** [comment]
hi, Do you want me to add a readme file about the Chinese version of
create-react-library?  If so, of course 😀

Travis Fischer <notifications@github.com> 于2018年7月7日周六 上午5:05写道：

**Comment by transitive-bullshit** [comment]
Yes, I'd love a pull request to add a Chinese readme 👍 Let me know if you have any questions!!

**Comment by monsterooo** [comment]
@transitive-bullshit yes , today i will create pr .🤔
